"""Fixed-policy paired support probe, also measured against original references."""
import json
from pathlib import Path
import numpy as np
D=Path('/home/pku/frankenmotion/outputs_amass/universal_tracker_20261006');old=D/'general_evaluation/natural_v4_3000';new=D/'general_evaluation/natural_support_projection_v4';before={r['source']:r for r in json.loads((old/'results.json').read_text())};after=json.loads((new/'results.json').read_text());manifest={r['source']:r for r in json.loads((D/'natural_support_projection/manifest.json').read_text())};records=[]
for r in after:
 b=before[r['source']];m=manifest[r['source']];z=np.load(Path(r['run'])/'actual.npz');ref=np.load(m['original_motion_path']);actual=z['body_pos_w'];n=len(actual);error=np.linalg.norm(actual[50:]-ref['body_pos_w'][50:n],axis=-1).mean(-1);accurate=bool(r['physical_complete'] and len(error)>0 and error.mean()<=.1 and np.quantile(error,.95)<=.25);unchanged=m['support_projection_frames']==0
 if unchanged:assert np.array_equal(z['qpos'],np.load(Path(b['run'])/'actual.npz')['qpos']),r['source']
 records.append(dict(source=r['source'],task=r['task'],reference_modified=not unchanged,before_complete=b['physical_complete'],after_complete=r['physical_complete'],after_accurate_against_original=accurate,post_entry_observed_frames=len(error),after_global_error_to_original_m=float(error.mean()) if len(error) else None,after_frame_mean_error_to_original_p95_m=float(np.quantile(error,.95)) if len(error) else None))
sumf=lambda key:sum(r[key] for r in records)
summary=dict(requests=len(records),modified=sumf('reference_modified'),before_complete=sumf('before_complete'),after_complete=sumf('after_complete'),after_accurate_against_original=sumf('after_accurate_against_original'),unchanged_exact_rollout_parity=sum(not r['reference_modified'] for r in records),newly_complete=sum(not r['before_complete'] and r['after_complete'] for r in records),lost_complete=sum(r['before_complete'] and not r['after_complete'] for r in records));out=dict(scope=__doc__,summary=summary,results=records,caution='A small development-only intervention with one policy. Does not certify reference feasibility, semantic preservation, or generalization. Never used to select final tracker or modify frozen-test references.');(D/'natural_support_projection_audit.json').write_text(json.dumps(out,indent=2));print(json.dumps(summary),flush=True)
