"""Index visually reviewed frozen-policy demos and preserve presentation selection disclosures."""
from pathlib import Path
import json,hashlib,datetime
ROOT=Path(__file__).resolve().parents[2];D=ROOT/'outputs/universal_tracker_20261006';V=D/'visuals';idx=json.loads((V/'frozen_candidates/candidate_index.json').read_text());videos=[]
def add(title,path,scope,commands,selection,review):
 p=V/path;assert p.exists();videos.append(dict(title=title,local_path=str(p.resolve()),sha256=hashlib.sha256(p.read_bytes()).hexdigest(),scope=scope,commands=commands,selection=selection,visual_review=review))
pair=next(r for r in idx['candidates'] if r['kind']=='table_pair')
add('同一权重：0.3 / 0.5 m reach 配对对比','frozen_candidates/fresh_table_paired.mp4','新随机布局测试中的展示样本，12/12 通过流程标准；视频不是成功率估计。',[dict(reach_command_human_m=r['scene']['command'],walk_distance_robot_m=r['scene']['distance_robot_m'],direction_rad=r['scene']['direction_rad'],turn_command_deg=r['scene']['turn_command_deg'],away_command_robot_m=r['scene']['away_command_robot_m'],actual=r['command_metrics'],run=r['run']) for r in pair['rows']],pair['selection'],'已检查两条流程的关键帧、接触特写与密集步态帧。可见 reach 距离不同、收手和离开；结合实际接触与抖动指标。未声称逐帧观看完整视频。')
commands=json.loads((D/'general_evaluation/frozen_demo_service_trimmed/command_metrics.json').read_text())['results']
for route in [0,1]:
 add(f'服务流程：走近、指向、鞠躬、右转{90 if route==0 else 135}度并离开',f'frozen_service_trimmed/service_{route}.mp4','FrankenMotion 生成片段组合；文本条件指向和鞠躬不是数值幅度控制。',[r for r in commands if r['route']==route],'预先生成的两个行走序列、指向 seed0/1；鞠躬取已生成 bend_09156_s1 的 20 Hz 帧80:144。时间裁剪与过渡已声明，无片段内姿态编辑。','关键帧可见伸臂、前屈与转身离开；route0 另检查了20帧连续步态与参考/实际对照。两条均完整执行，未据此声明任意文本均可生成。')
nav=json.loads((D/'general_evaluation/frozen_demo_navigation/command_metrics.json').read_text())['results']
for route in [0,1]:
 add(f'连续相对命令：路线{route+1}与挥手',f'frozen_candidates/navigation_route_{route}.mp4','多段生成命令与实际状态参考锚定；没有视觉感知或扩散闭环重规划。',[r for r in nav if r['route']==route],'两个预先定义的路线全部展示，未按最终误差另选权重。','已检查各阶段关键帧；可见转向、步行和挥手，实际路径与初始参考差异保留。')
add('11类动作：固定首个来源与中间命令','eleven_grid/eleven_actions.mp4','880条基准中的确定性示例；包含出拳、踢腿、跳跃不达标项。',json.loads((V/'eleven_grid/protocol.json').read_text())['records'],'每类 p0_s0_c2，无成功筛选。','四个时间截面的11格画面已检查。失败状态直接显示，短片结束后保持最后帧且标注 FINISHED / HELD；各片均1×速度。')
add('文本生成指向：参考与物理执行对照','frozen_candidates/point_point_01584_s0/reference_vs_physics.mp4','左为运动学参考，右为实际物理执行；不包含手指关节控制。',dict(prompt='a person raises their right arm to point at something ahead',numeric_command=None),'4条完成的生成指向候选均归档；本条用于清晰的参考/实际对照。','6个时间截面可见右臂抬起、前伸与放下，跟踪差异没有掩盖。')
reel=V/'presentation_reel/one_minute_demo.mp4'
if reel.exists():
 add('一分钟演示合集：参数化桌面交互与服务动作','presentation_reel/one_minute_demo.mp4','两个独立场景的完整视频拼接，共59.8秒，均为1×速度；没有把它们伪装成一次连续执行。',dict(scene1='配对reach0.3/0.5m，走近—接触—收手—转90度—离开1.2m',scene2='走近1m—文本指向—生成鞠躬片段—右转90度—离开0.8m'),'采用已经完整评估并视觉检查的桌面配对与服务route0；不是新的测试样本。','标题卡、两个片段中间帧与结尾卡已检查。完整源视频均保留，源哈希和逐片起止帧见同名JSON。');videos.insert(0,videos.pop())
review=dict(created_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),checkpoint_sha256=json.loads((D/'frozen_unified/protocol.json').read_text())['checkpoint_sha256'],scope='Visual reviews use archived actual-pose keyframes/dense gait strips plus numerical evidence; not a claim of watching every frame, naturalness certification or broad semantic success.',rejected=[dict(group='clean_bow',count=2,reason='No meaningful generated forward bow: human torso increase <1 degree, despite physical completion.'),dict(group='clean_bend',count=2,reason='No meaningful generated forward bend: human torso increase <1 degree, despite physical completion.'),dict(group='clap',reason='No verified palm-to-palm clap; observed hand-to-opposite-wrist contacts insufficient.')],superseded=[dict(group='service_full',reason='Complete rollout, but initial T-pose and multiple turns distract from intended service sequence. Full attempts retained.')],videos=videos)
retreat=V/'frozen_retreat/retreat_0.mp4'
if retreat.exists():
 review['diagnostic_videos']=[dict(title='探索性组合：后退与侧移（侧移朝向未达标）',local_path=str(retreat.resolve()),sha256=hashlib.sha256(retreat.read_bytes()).hexdigest(),scope='Whole physical rollout completed. Backward command0.625m/s measured0.5965; sidestep command0.8m measured0.7490m, but heading change0.55410rad exceeds fixed0.55rad gate. Not promoted as an all-commands-passed demo.',commands=json.loads((D/'general_evaluation/frozen_demo_retreat/command_metrics.json').read_text())['results'],visual_review='All stage keyframes inspected: walking, pointing, retreat, side-step and turn visible. Small heading drift retained; numerical gate unchanged.',selection='One post-test composition using fixed first fresh source/middle commands, one frozen actor. No retries or weight changes.')]
long_video=V/'frozen_long_horizon/long_horizon_comparison.mp4'
if long_video.exists():
 review.setdefault('diagnostic_videos',[]).append(dict(title='134秒连续命令：相对参考锚定与固定世界参考对照',local_path=str(long_video.resolve()),sha256=hashlib.sha256(long_video.read_bytes()).hexdigest(),scope='Same six generated clips repeated four times, 24 stages. Both complete; one physical trial per interface mode. Initial-world-plan endpoint deviations0.717m/0.036m. Relative anchors intentionally update the plan; not tracking error against the adapted reference, not24 independent samples.',commands=json.loads((D/'long_horizon_ablation.json').read_text()),visual_review='All stage keyframes reviewed in source rollouts; follow camera keeps full body visible. Four comparison timestamps inspected with mode labels. Whole trajectories at1x speed, no state reset.',selection='Fixed route0 repeatedfourtimes, same frozen actor, one run per anchoring mode; no weight or reference selection. Firsttwo invocation attempts failed before physics due to missing native-motion input; standard FK conversion fixed the interface.'))
(D/'video_index.json').write_text(json.dumps(review,ensure_ascii=False,indent=2));print('Indexed',len(videos),'reviewed videos')
