"""Portable local gallery for reviewed videos, figures and the Chinese report."""
from pathlib import Path
import json,html,shutil
ROOT=Path(__file__).resolve().parents[2];D=ROOT/'outputs/universal_tracker_20261006';idx=json.loads((D/'video_index.json').read_text());escape=html.escape;cards=[]
for r in idx['videos']+idx.get('diagnostic_videos',[]):
 p=Path(r['local_path']);rel=p.relative_to(D).as_posix();poster=p.with_suffix('.png');poster_attr=f' poster="{escape(poster.relative_to(D).as_posix())}"' if poster.exists() else ''
 cards.append(f'<article><h2>{escape(r["title"])}</h2><video controls preload="none"{poster_attr} src="{escape(rel)}"></video><p>{escape(r["scope"])}</p><details><summary>命令、选择方式与视觉检查</summary><p>{escape(r.get("selection",""))}</p><p>{escape(r.get("visual_review",""))}</p><pre>{escape(json.dumps(r["commands"],ensure_ascii=False,indent=2))}</pre></details><a href="{escape(rel)}">打开原始视频</a></article>')
pdf=ROOT/'output/pdf/universal_tracker_20261006/统一Tracker扩展实验报告_中文.pdf';(D/'报告').mkdir(exist_ok=True);shutil.copy2(pdf,D/'报告'/pdf.name)
text='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FrankenMotion → G1：统一 Tracker 实验</title><style>body{font:16px/1.65 system-ui,-apple-system,sans-serif;margin:0;background:#edf2f6;color:#152b3a}main{max-width:1120px;margin:auto;padding:36px 22px}h1{font-size:32px;line-height:1.3}h2{font-size:20px}a{color:#087f9c}header,article,.figure{background:white;padding:24px;border-radius:12px;margin-bottom:24px}video,img{width:100%;max-height:660px;object-fit:contain;background:#101b2a;border-radius:6px}pre{overflow:auto;max-height:360px;background:#f1f4f7;padding:16px;font-size:12px}details{margin:16px 0}small{color:#526d7b}.stats{font-size:18px;font-weight:600;color:#09687d}</style><main><header><small>2026-10-06 · 冻结权重 v5_final · 未 push</small><h1>FrankenMotion → G1<br>一套共享 Tracker 的联合训练与扩展实验</h1><p class="stats">新噪声命令联合通过 511/880（旧共享版 444/880） · 新桌面流程 12/12</p><p>严格类别门槛仍只有 3/11 类达标；自然动作严格通过 9/54，未超过旧共享版 11/54。第二训练种子类别波动明显。20 ms 执行延迟下，长流程在 103.42 s 终止。展示成功不代表通用覆盖或真机就绪。</p><p>视频均为实际物理轨迹的 1×回放；参考对照、片段裁剪和重复使用均单独声明。生成与重定向离线完成，G1 使用固定手部模型。</p><p><a href="报告/统一Tracker扩展实验报告_中文.pdf">中文实验报告（19页）</a> · <a href="交付说明.txt">交付与复现说明</a> · <a href="tables/fresh_880_all_controllers.csv">逐条测试数据</a></p></header>'''+''.join(cards)+'''<section class="figure"><h2>11 类参数响应：生成 → 重定向 → 物理执行</h2><a href="figures/final_all/command_response.png"><img src="figures/final_all/command_response.png" alt="11类命令响应曲线"></a><p>完整 PDF/SVG 与分组图保留在 figures 目录；误差带为来源的 P10–P90，不是训练种子置信区间。</p></section></main></html>'''
# Use the actual final_all figure name rather than assume a basename.
figs=sorted((D/'figures/final_all').glob('*.png'));assert len(figs)==1;text=text.replace('figures/final_all/command_response.png',figs[0].relative_to(D).as_posix())
(D/'演示索引.html').write_text(text);print(D/'演示索引.html')
