from pathlib import Path
import json,html,hashlib
D=Path('/home/pku/frankenmotion/outputs_amass/unified_commands_20261007');out=D/'report';s=json.loads((out/'summary.json').read_text());scene=json.loads((out/'scene_summary.json').read_text());lock=json.loads((D/'selection_lock.json').read_text());ea=json.loads((D/'exports/candidate_v4/export_audit.json').read_text());tasks=['raise_hand','reach','strike','wave','turn','sidestep','back_walk','kick','jump','lean','walk'];cn=['抬手','前伸','出拳速度','挥手幅度','右转','右侧移','后退','右踢腿','跳跃','保持前倾','前进'];ranges=['0.35–0.75 m','0.25–0.55 m','1.5–2.5 m/s','0.08–0.22 m','0.45–1.5 rad','0.4–1.2 m','0.35–0.9 m/s','0.25–0.7 m','0.25–0.55 m','0.4–0.9 rad','0.5–1.1 m/s'];rows=''
for t,c,r in zip(tasks,cn,ranges):
 x=s['per_kind'][t];a=x['human'];bp=x['physical_before'];sp=x['physical_after'];rows+=f'<tr><td>{c} / {t}</td><td>{r}</td><td>{a["baseline"]["joint_pass"]} → {a["human"]["joint_pass"]} / 80</td><td>{bp["joint_pass"]} → {sp["joint_pass"]} / 80</td><td>{a["mean_joint_position_error_m"]*1000:.2f} mm</td><td><a href="../visuals/unified_final/{t}.mp4">人体对照</a> · <a href="../visuals/g1_unified_final/{t}_c2/reference_vs_physics.mp4">G1</a></td></tr>'
tb=scene['baseline_final'];ts=scene['unified_final'];n=s['standard_requests'];drop=(s['human_before']-s['human_after'])/n*100;pd=(s['physical_before']-s['physical_after'])/n*100;permax=max((s['per_kind'][t]['physical_before']['joint_pass']-s['per_kind'][t]['physical_after']['joint_pass'])/80*100 for t in tasks);checks=dict(human_drop_pp=drop,physical_drop_pp=pd,max_per_task_drop_pp=permax,human_mean_difference_mm=s['human_mean_joint_difference_mm'],table_success_drop=tb['successes']-ts['successes']);checks['near_baseline']=drop<=3 and pd<=3 and permax<=10 and checks['human_mean_difference_mm']<=10 and checks['table_success_drop']<=1;(out/'acceptance_checks.json').write_text(json.dumps(checks,indent=2))
extra=''
for k in ['walk_endpoint','place_hold_retract','back_departure','side_departure','root_profile','turn_endpoint']:
 z=s['per_kind'][k];extra+=f'<tr><td>{k}</td><td>{z["human"]["count"]}</td><td>{z["human"]["mean_joint_position_error_m"]*1000:.2f} mm</td><td>{z["physical_before"]["complete"]} → {z["physical_after"]["complete"]}</td><td><a href="../visuals/unified_final/{k}.mp4">人体对照</a></td></tr>'
text=f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>统一参数化命令权重：训练与对照报告</title><style>body{{max-width:1120px;margin:40px auto;padding:0 24px;font:16px/1.7 -apple-system,BlinkMacSystemFont,"Noto Sans CJK SC",sans-serif;color:#183047;background:#f7f9fc}}h1{{font-size:32px}}h2{{margin-top:38px}}table{{border-collapse:collapse;width:100%;font-size:14px;background:white}}td,th{{border:1px solid #dce4ed;padding:10px;text-align:left}}th{{background:#eaf0f6}}a{{color:#186db1}}pre{{white-space:pre-wrap;background:#eaf0f6;padding:18px}}.cards{{display:flex;gap:16px}}.card{{flex:1;background:white;border:1px solid #dce4ed;border-radius:12px;padding:18px}}img{{max-width:100%}}small{{color:#536778}}</style>
<h1>FrankenMotion：统一参数化命令权重</h1><p>2026-10-08 · 已冻结候选权重后完成新随机种子评估 · 未 push</p>
<div class="cards"><div class="card"><b>人体命令＋事件通过</b><br>{s['human_before']}/{n} → {s['human_after']}/{n}</div><div class="card"><b>同一 G1 tracker 通过</b><br>{s['physical_before']}/{n} → {s['physical_after']}/{n}</div><div class="card"><b>随机桌边完整流程</b><br>{tb['successes']}/{tb['planned']} → {ts['successes']}/{ts['planned']}</div></div>
<p>本轮把 RootControl、当前11类共享任务适配器、GoalControl、ReachControl、ExitControl 的参数化控制统一到一个共享网络中。所有任务使用同一文件、同一网络；不按动作加载不同权重。旧权重已逐份复制并校验 SHA-256。</p>
<p>与当前分开控制模块的基线相比，人体参考平均关节位置差为 <b>{s['human_mean_joint_difference_mm']:.2f} mm</b>，每条片段平均误差的 P95 为 {s['human_p95_clip_mean_joint_difference_mm']:.2f} mm。全数据中最差单帧单关节差为 {s['human_max_frame_joint_difference_mm']:.2f} mm。这里的误差衡量“是否保留旧行为”，不能单独证明旧行为自然或任务执行正确。</p>
<h2>1. 这次合并了什么</h2><p>基础11类包含抬手、前伸、出拳、挥手、转身、侧移、后退、踢腿、跳跃、前倾、前进。另包含独立根速度／角速度曲线、走路终点距离和方向、指定伸手距离及高度的放手—保持—收手完整片段、起停后退／侧移、大角度转身。共17种评估场景，不代表17套网络。</p>
<table><tr><th>额外控制</th><th>共享控制器训练采样范围</th><th>说明</th></tr><tr><td>根速度与转向角速度</td><td>0–3 m/s；−π–π rad/s</td><td>两个独立有效性标记。原 RootControl 由1秒窗口平均信号训练；逐帧精确跟踪并非既有保证。</td></tr><tr><td>终点距离与方向</td><td>人体距离0.8–2.8 m；方向±0.65 rad</td><td>6秒片段；通过既有坐标和身高换算构造速度／角速度曲线。</td></tr><tr><td>桌面放手—收手</td><td>前伸0.28–0.52 m；手高度0.81–0.87 m</td><td>前伸为人体等效值，高度为机器人目标坐标；完整6秒片段由生成模块控制。</td></tr><tr><td>起停后退／侧移</td><td>后退0.28–0.42 m/s；侧移0.4–0.7 m</td><td>包含旧 ExitControl 每个去噪步的205维输出残差。</td></tr><tr><td>大角度右转</td><td>训练输入1.5–4.5 rad；评估90°/135°/180°</td><td>复合桌边测试使用90°/135°，直接参考测试含180°。</td></tr></table>
<p>这些是已定义的控制语义和组合。本轮没有证明任意未训练的动作、参数组合、时长或越界命令都能保持效果。</p>
<h2>2. 一份权重内部的结构</h2><pre>文本特征、噪声 ───────────────► 冻结 FrankenMotion 扩散去噪器（4个Transformer块）
                                               ▲  ▲  ▲  ▲           ▲
任务/意图/命令/有效性/时间（46维）                │  │  │  │           │
        │                                      │  │  │  │           │
        ▼                                      │  │  │  │           │
共享编码器：46 → 1024 → 1024                    │  │  │  │           │
        ├── 四个共享位置输出头：1024 → 1024 → 512 ┘  ┘  ┘  ┘           │
        └── 共享去噪输出头：1024 → 1024 → 205 ────────────────────────┘

生成的原始人体运动 → GMR / 既有参考处理 → 同一个冻结 G1 tracker → MuJoCo</pre>
<p>四个512维输出头对应四个 Transformer 注入位置，所有动作都运行这些头；不是 walk、jump、kick 各有一个专家。205维输出头同样共享。任务和片段意图是网络的条件输入，不是权重路由。没有命令时由统一有效性门控给出零残差。</p>
<p>FrankenMotion 主干保持冻结，训练的是共享控制网络（{ea['controller_parameters']:,} 个参数）。发布文件包含主干、共享控制网络和归一化统计量，约90 MiB。文本编码与 SMPL 渲染资产、物理 tracker 仍是不同用途的组件；“一份”指动作生成侧的所有参数化控制权重，不把 tracker 或 SMPL 伪装成同一个模型。</p>
<h2>3. 怎么训练和验证</h2><p>原有控制器都在同一组 Transformer 块上添加条件残差。首先将旧分支实际叠加的残差和去噪输出残差重建为冻结教师；17场景同噪声重放与原代码的最大关节位置差为1.43微米。随后用连续随机命令、随机时间点及起止时刻训练一个密集共享网络逼近这些教师函数。没有把旧控制器直接装进新文件，也没有改动 tracker。</p>
<table><tr><th>版本</th><th>训练</th><th>开发集物理通过 /110</th></tr><tr><td>旧分开模块</td><td>冻结基线</td><td>80</td></tr><tr><td>v1</td><td>宽度512，20k步</td><td>77</td></tr><tr><td>v2</td><td>v1低学习率精修30k步</td><td>78</td></tr><tr><td>v3</td><td>宽度1024，30k步，加入片段起止采样</td><td>80</td></tr><tr><td>v4（锁定）</td><td>v3以5e−6精修40k步</td><td>81</td></tr></table>
<p>最终评估共1376条请求／方案：基础11类每类80条（4个提示模板×4个噪声种子×5档命令），额外控制共496条。放手收手只有2种独立文本模板，使用新噪声，不能算4种独立文本。新模型全部通过独立导出文件加载。双方完成仿真数为 {s['completed_before']} → {s['completed_after']} /1376；“完成仿真”不等于命令、语义或接触成功。</p>
<p>最终物理通过率变化 {s['paired_physical_pass_change_pp']:+.2f} 个百分点；按16个提示／噪声块做配对重采样的描述性95%区间为 {s['paired_source_bootstrap_95ci_pp'][0]:+.2f} 至 {s['paired_source_bootstrap_95ci_pp'][1]:+.2f} 个百分点。评估依赖固定提示库和冻结 tracker，不作为全面泛化或统计非劣性证明。预先锁定的“接近旧效果”检查结果：<b>{'通过' if checks['near_baseline'] else '未全部通过，请查看 acceptance_checks.json'}</b>。</p>
<h2>4. 各动作结果</h2><table><tr><th>动作</th><th>参数范围</th><th>人体通过：旧→新</th><th>G1通过：旧→新</th><th>人体平均差</th><th>视频</th></tr>{rows}</table><p>通过要求同时满足旧事件检查和命令误差容限。并非所有旧动作都很好；尤其低通过项应继续分析生成参考和 tracker。完整计数与额外控制指标见 <a href="summary.json">summary.json</a>。</p><img src="command_curves.png" alt="11类命令响应对照曲线"><p><a href="command_curves.pdf">矢量PDF曲线</a>。中线为中位数，阴影P10–P90。曲线展示可测量输出，不筛选成功样本。</p>
<h2>5. 额外控制和桌边流程</h2><table><tr><th>控制场景</th><th>请求数</th><th>人体参考平均差</th><th>仿真完成：旧→新</th><th>视频</th></tr>{extra}</table>
<p>随机抽取8个新的桌边布局，每个布局配对0.3 m和0.5 m前伸命令，共16段完整流程。原方案成功 {tb['successes']}/16，统一方案 {ts['successes']}/16。统一方案两档实际保持前伸均值分别为 {ts['reach_commands']['0.3']['mean']:.3f} m 和 {ts['reach_commands']['0.5']['mean']:.3f} m。</p>
<p>复合流程保留历史的输入命令迭代修正（依据生成终点，最多3次修正）、GMR、走路重定时、片段刚体放置／拼接、最终站姿过渡和因果参考锚定。两组完全相同。没有对本轮新生成结果追加手臂IK；但旧训练目标中的接触、时序支撑、步态先验被蒸馏保留，不能宣称本轮消除了它们。平地通用评估不使用桌边参考锚定。</p>
<p><a href="../visuals/table/scene_000.mp4">布局1：reach 0.3 m</a> · <a href="../visuals/table/scene_001.mp4">布局1：reach 0.5 m</a> · <a href="../visuals/table/scene_002.mp4">布局2：reach 0.3 m</a> · <a href="../visuals/table/scene_003.mp4">布局2：reach 0.5 m</a> · <a href="scene_summary.json">完整逐场景数据</a></p>
<p>根速度曲线的逐帧MAE约0.333→0.332 m/s，角速度MAE约0.206→0.207 rad/s；这项旧能力本身较弱。直接距离命令的终点平均误差约5.98→6.06 cm。桌边demo有输入命令修正，因此不能用它的成功率代替未经修正的原始生成误差。</p><p>桌边前进段躯干角速度的5Hz高通RMS均值约0.09482→0.09479 rad/s，离开段约0.08376→0.08190 rad/s；前进段关节速度高频均值0.345→0.363 rad/s。指标有升有降，不能据此声称完全消除了抖动。</p><h2>6. 失败样本与视觉检查</h2><p>旧模型提前终止6条，新模型4条。其中1条两者都失败，5条旧失败在新模型中完成，3条旧完成在新模型中失败。新增终止为 jump_p3_s2_c4、walk_p0_s0_c4、walk_p0_s2_c4。几何参考接近不保证非线性物理执行逐条相同；本轮保留这些失败，没有重新选权重或用最终集微调。</p><p><a href="../visuals/failure_pairs/walk_p0_s0_c4.mp4">高速走路：旧完成、新失稳</a> · <a href="../visuals/failure_pairs/jump_p0_s0_c4.mp4">大跳：旧新都失稳</a>。失败后仅保留最后记录状态，并在视频中标明 TERMINATED，不伪造后续动作。踢腿中档人体参考还存在收腿不充分／幅度偏小，这也是旧方案中已有的不足。</p><h2>7. 交付、复现与边界</h2><p><a href="../delivery/unified_generator.pt">统一权重</a> · <a href="../delivery/runtime/shared_infer.py">独立推理入口</a> · <a href="../delivery/export_audit.json">导出审计</a> · <a href="../delivery/isolated_audit.json">独立进程加载审计</a> · <a href="../delivery/standalone_parity.json">17场景推理一致性</a></p><pre>SHA-256: {lock['sha256']}
远程实验目录：{D}
远程脚本目录：/home/pku/frankenmotion/work/unified_commands_20261007
旧权重备份：{D}/backup
旧权重校验：{D}/backup_manifest.json</pre>
<p>旧权重和现有默认入口未覆盖；本轮没有 push。渲染使用存档的人体姿态或实际物理状态，未用参考姿态替代执行。视频预先指定第一组提示／噪声及若干命令档位，不按成功筛选；视觉检查范围和发现另见 <a href="visual_review.json">visual_review.json</a>。这次完成的是现有控制能力的统一和保留，并不意味着跳跃、踢腿等所有动作已达到可部署真机的质量。</p></html>'''
(out/'report_zh.html').write_text(text);print(checks)
