import json,numpy as np
from pathlib import Path
R=Path('/home/pku/frankenmotion');D=R/'outputs_amass/reach_demo_20261005';F=D/'final_paired16';P=D/'report';P.mkdir(exist_ok=True);proto=json.loads((D/'frozen/protocol.json').read_text());rows=json.loads((F/'manifest.json').read_text());data={}
for name in ['selected','selected_cpu']:
 data[name]=[json.loads((Path(x['source'])/name/'result.json').read_text()) for x in rows]
lines=['FrankenMotion → G1：生成命令驱动的 reach / 放手 / 离开 demo','','一、实现','reach 数值进入 FrankenMotion 的学习型条件分支，生成抬手、前伸、接触、保持、抬离、回收和放下整段动作。推理时没有桌面目标驱动的手部 scene-aware IK。后退速度、侧移距离也输入学习型生成分支。GMR 本身仍是 IK 重定向，不能称为整个流水线没有 IK。','同一固定 tracker 执行所有阶段，没有按动作选择控制权重、执行时教师或权重混合，也没有用参考状态覆写物理机器人。','','二、命令单位','reach=.30/.50m 表示保持阶段右手腕相对骨盆的前向距离，使用 human-equivalent 单位。G1 实际手腕距离需乘1.0486437524221748/1.2701193988323212≈0.826，手掌还包含几何偏移。这不是机器人手掌移动了30/50厘米，也不是任意世界坐标的三维reach目标。','walk距离为G1根水平移动米数，方向为平面朝向；back=.35是人体等效后退速度m/s，side=.50是人体等效侧向位移m。','','三、最终测试','冻结策略：'+proto['source_checkpoint'],'reach生成器：'+proto['source_generator'],'离开生成器：'+proto['source_exit_generator'],'8个新随机布局，各比较相同噪声/行走/离开条件下的reach=.3/.5，共16条。桌高0.8m、已知桌位、平地和标称物理。最终结果不用于继续拟合。']
for name,rr in data.items():
 m=[r['command_metrics'] for r in rr];errors=[r['command_error_m'] for r in m if r['command_error_m'] is not None]
 lines.append(f'{name}: 成功{sum(r["success"] for r in rr)}/{len(rr)}，完整未跌倒{sum(r["physical_complete"] for r in rr)}/{len(rr)}，平均reach绝对误差{np.mean(errors):.4f}m。')
 for c in [.3,.5]:
  v=[r['actual_hold_wrist_forward_human_equiv_m'] for r in m if abs(r['command_human_equiv_m']-c)<1e-6 and r['actual_hold_wrist_forward_human_equiv_m'] is not None];lines.append(f'  command={c:.2f}: 实际均值{np.mean(v):.4f}m，标准差{np.std(v):.4f}m。')
 lines.append('  失败索引：'+str([i for i,r in enumerate(rr) if not r['success']]))
lines+=['成功条件：完整执行；保持阶段连续真实桌面接触≥0.5s；reach误差≤0.08m；保持阶段根误差<0.15m；手掌下降>0.10m；离开方向投影位移>0.25m。接触由MuJoCo法向、位置和力>0.2N计算。这不是自然度评分，步态另做视觉和脚底指标检查。result.json中旧的末帧palm_target_error/goal_error在机器人离开桌子后自然变大；reach应读取command_metrics内的保持阶段指标，不能用末帧离桌距离代替。','','四、训练与工程处理','ReachControl冻结原始骨干，使用FK手部时序监督，包括固定桌高的命令相关高度校准和学习型接触预压。不是通用真实交互数据训练。','ExitControl使用条件latent残差和denoiser内部的学习型输出残差；训练监督含交替支撑/摆动脚目标、膝屈曲及朝向；最后一版保留侧移脚间距，并加入与支撑相位同步的横向重心目标。推理采样后没有显式合成腿部轨迹。','GMR对reach使用手腕位置/方向权重80/5，行走uniform重定向。离开段根Z按精确脚底碰撞胶囊贴合平地，保留关节角与根XY。另有XY/yaw放置、片段拼接、起停站姿过渡及行走/侧移时间重采样。阶段按参考时间表衔接，不是检测接触后才触发下一个动作的任务规划器。这是分阶段流水线，不是端到端场景策略。','统一tracker继续PPO训练：709条参考包括645条旧普通动作、16条旧桌面参考和48条新生成序列。旧桌面训练回放含scene-aware IK数据；新展示手部参考没有此处理。','','五、证据与复现','videos为选出的完整物理执行及同场景reach对照，按1x时间播放，渲染未修改或平滑轨迹。演示样例不代表总成功率。','evidence保留全部最终GPU/CPU轨迹、控制、观察、接触和审计，包含失败。CPU独立重建361维观察，使用同一导出actor。审计含原生动力学单周期重算。','README提供已有服务器生成新demo及独立Linux CPU示例。基础生成器资产、完整训练环境仍依赖服务器现有安装，发布包不是可迁移一键训练环境。','','六、局限','只验证已知桌位、固定桌高和平地标称仿真；未验证感知、各种桌高/材质、扰动、真机及完整旧技能保持。训练目标经过开发集校准，不应声称零样本泛化。步态及过渡质量以随附视觉检查记录为准。','代码和实验未自动push。']
(P/'实验说明.txt').write_text('\n'.join(lines)+'\n');(P/'results.json').write_text(json.dumps({name:[r['command_metrics'] for r in rr] for name,rr in data.items()},indent=2));print(P/'实验说明.txt')
