import json,subprocess
from pathlib import Path
import imageio.v2 as imageio,imageio_ffmpeg
D=Path('/home/pku/frankenmotion/outputs_amass/reach_demo_20261005');videos=D/'videos';checks={};ff=imageio_ffmpeg.get_ffmpeg_exe()
for name in ['funding_demo.mp4','reach_030_vs_050.mp4','side_departure_full.mp4','back_departure_full.mp4']:
 p=videos/name;subprocess.run([ff,'-v','error','-i',str(p),'-f','null','-'],check=True,stdout=subprocess.DEVNULL);reader=imageio.get_reader(p);meta=reader.get_meta_data();reader.close();checks[name]=dict(full_decode_passed=True,fps=meta['fps'],size=meta['size'],duration_s=meta.get('duration'))
review=dict(method='Assistant visual inspection of paired reach phase contact sheets, complete-rollout keyframes, 24-frame unobstructed walking/side-departure strips, and 4-stage overviews covering all16 GPU cases. Quantitative native-physics audits independently check contact and dynamics. This is visual inspection of sampled frames, not a validated human naturalness study.',presentation_cases=json.loads((videos/'selection.json').read_text()),findings=['Near/far reach differs visibly with same scene/noise; held phase contacts the table and then retracts clear before lowering.','Selected walking and side departure show alternating leg movement; arm lowering finishes before departure.','No falling or obvious hand-through-table artifact visible in sampled final frames; physical penetration/contact values are in audits.','Backward departure retains left/right step asymmetry and some shuffling; retained as supplementary prototype, omitted from main funding edit.','Contact is by the hand collision geometry. Finger articulation, grasping, and an opened palm lying flat are not demonstrated.','Minor body sway, posture transitions and residual foot slip remain; the result demonstrates a nominal simulation pipeline, not hardware readiness.'],video_checks=checks,approved_for='Simulation pipeline presentation focused on generated reach and side departure; limits must accompany the results')
(D/'visual_review/review.json').write_text(json.dumps(review,indent=2));(D/'visual_review/视觉检查.txt').write_text('已检查：同场景0.3/0.5 reach关键帧、完整侧移demo的阶段画面、无遮挡24帧行走和侧移序列，以及16条场景的四阶段总览。\n伸手远近、真实桌面接触、抬离回收、手臂放下和侧移的先后关系清楚。选定侧移具有交替抬脚。\n后退仍有左右脚不对称和拖步，作为补充原型，未放入主汇报片。手部碰撞接触不等于张开手掌完全平贴；没有手指抓握。轻微身体摇摆和脚底滑动仍存在。\n视频已完整解码检查；主片仅拼接标题卡、同场景reach对比和一条不中断的侧移全流程，物理画面1x播放，无轨迹修正。\n')
with (D/'report/实验说明.txt').open('a') as f:f.write('\n七、视觉检查结论\n主片采用case10/11的配对reach和case11完整侧移流程。已检查全部16条四阶段画面，以及主片所用行走/侧移的无遮挡逐帧序列。后退版仍有左右脚不对称和部分拖步，单独保留为补充原型，未放进主汇报视频。手部接触不代表张开手掌完全平贴，也没有抓握功能。轻微摇摆与滑动仍需改进。视频完整解码通过。\n额外CLI复现检查：reach=.4、行走1.2m、方向10°、侧移.5，成功完成；实际人体等效reach=.4378m。该案例不计入16条最终配对统计。\n')
print(json.dumps(checks,indent=2))
