import os,sys,json,hashlib,argparse
from pathlib import Path
os.environ['MUJOCO_GL']='egl'
R=Path('/home/pku/frankenmotion');D=R/'outputs_amass/reach_demo_20261005';sys.path[:0]=[str(R/'work'),str(R/'outputs_amass/franken_eleven_20261003/code')]
import torch,numpy as np,mjlab.tasks
from scipy.spatial.transform import Rotation,Slerp
from mjlab.tasks.registry import load_env_cfg
from mjlab.envs import ManagerBasedRlEnv
from mjlab_cpu_fk_20261003 import convert_cpu
import transfer as tr
p=argparse.ArgumentParser();p.add_argument('--folder',required=True);p.add_argument('--name',required=True);a=p.parse_args();folder=Path(a.folder);out=D/a.name;out.mkdir(exist_ok=False);torch.set_num_threads(2);cfg=load_env_cfg('Mjlab-Tracking-Flat-Unitree-G1',play=True);cfg.scene.num_envs=1;cfg.commands['motion'].motion_file=str(R/'work/beyondmimic_demo_motion.npz');cfg.sim.nconmax=256;cfg.sim.njmax=2048;e=ManagerBasedRlEnv(cfg=cfg,device='cuda:0');robot=e.scene['robot'];m=tr.rt.load_model();names=[m.joint(i).name for i in range(1,m.njnt)];order=[names.index(n) for n in robot.joint_names];old=json.loads((R/'outputs_amass/gait_demo_20261005/training_corpus_timed/manifest.json').read_text());records=[r for r in old if r['task'] not in ['table_approach','back_walk','sidestep']]+[r for r in old if r['task']=='table_approach'][:16];prior_count=len(records);clips=[dict(np.load(r['motion_path'])) for r in records]
for row in json.loads((folder/'manifest.json').read_text()):
 s=Path(row['source']);states=np.load(s/'reference_contact.npz')['reference_qpos'];t=np.arange(len(states))*.05;tt=np.arange(int(np.ceil(t[-1]/.02))+1)*.02;ts=np.minimum(tt,t[-1]);pos=np.stack([np.interp(ts,t,c) for c in states[:,:3].T],1);rots=Slerp(t,Rotation.from_quat(states[:,[4,5,6,3]]))(ts);quat=rots.as_quat()[:,[3,0,1,2]];q=np.stack([np.interp(ts,t,c) for c in states[:,7:].T],1)[:,order];dq=np.gradient(q,.02,axis=0);vel=np.gradient(pos,.02,axis=0);av=(rots[1:]*rots[:-1].inv()).as_rotvec()/.02;av=np.r_[av,av[-1:]];path=out/f'table_generated_{row["index"]:03d}.npz';convert_cpu(e,robot,pos,quat,q,dq,vel,av,rots,path);clips.append(dict(np.load(path)));records.append(dict(task='table_approach',seed=row['seed'],motion_path=str(path),frames=len(q),scene_metadata=row,reference_metadata=json.loads((s/'reference_contact.json').read_text()),reference_sha256=hashlib.sha256((s/'reference_contact.npz').read_bytes()).hexdigest(),source_type='generated_reach_lower_exit_no_scene_ik'));print('converted',row['index'],flush=True)
ends=np.cumsum([len(x['joint_pos']) for x in clips]);np.savez_compressed(out/'training_motions.npz',fps=50.,**{k:np.concatenate([x[k] for x in clips]) for k in clips[0] if k!='fps'});(out/'manifest.json').write_text(json.dumps(records,indent=2));(out/'clips.json').write_text(json.dumps(dict(ends=ends.tolist(),records=records),indent=2));(out/'audit.json').write_text(json.dumps(dict(prior_generic_clips=prior_count-16,prior_table_clips=16,new_generated_clips=len(records)-prior_count,frames=int(ends[-1]),scope='Training-only references; no development or final generated examples'),indent=2));e.close();print('COMPLETE',len(records),flush=True)
