"""Stage-wise command and tabletop interaction metrics, allowing release and departure."""
import json,argparse,numpy as np,mujoco
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--run',required=True);a=p.parse_args();run=Path(a.run);r=json.loads((run/'result.json').read_text());meta=json.loads((run.parent/'reference_contact.json').read_text());z=np.load(run/'actual.npz');ref=np.load(run/'motion.npz');seg=meta['segments'];ph=z['phases'][:len(z['qpos'])];m=mujoco.MjModel.from_binary_path(str(run/'scene.mjb'));d=mujoco.MjData(m);wrist=m.joint('robot/right_wrist_yaw_joint').id;pelvis=m.body('robot/pelvis').id;hand=m.geom('robot/right_hand_collision').id;table=m.geom('table_top').id;forward=np.array([np.cos(r['scene']['direction_rad']),np.sin(r['scene']['direction_rad']),0]);measure=[];flags=[];root=[];palm=[]
for i in range(len(ph)):
 d.qpos[:]=z['qpos'][i];d.qvel[:]=z['qvel'][i];d.ctrl[:]=z['ctrl'][i];d.qacc_warmstart[:]=0;mujoco.mj_forward(m,d);root.append(d.xpos[pelvis].copy());palm.append(d.geom_xpos[hand].copy());measure.append(float(np.dot(d.xanchor[wrist]-d.xpos[pelvis],forward))*1.2701193988323212/1.0486437524221748);touch=False
 for j in range(d.ncon):
  c=d.contact[j]
  if hand in c.geom and table in c.geom:
   f=np.zeros(6);mujoco.mj_contactForce(m,d,j,f);touch|=bool(c.pos[2]>r['scene']['table_top']-.012 and abs(c.frame[2])>.8 and d.geom_xpos[hand,2]>r['scene']['table_top'] and f[0]>.2)
 flags.append(touch)
root=np.array(root);palm=np.array(palm);flags=np.array(flags);measure=np.array(measure)
def mask(name):
 lo,hi=seg[name];return (ph>=lo*2.5)&(ph<hi*2.5)
hold=mask('contact_hold');reach=mask('reach_place_lower');lower=mask('retract_lower');exitmask=mask('exit');lastlower=np.flatnonzero(lower)[-10:];contactflags=flags&reach;longest=count=0
for t in contactflags:count=count+1 if t else 0;longest=max(longest,count)
holdlongest=holdcount=0
for t in flags&hold:holdcount=holdcount+1 if t else 0;holdlongest=max(holdlongest,holdcount)
held=palm[hold];lowerz=float(palm[lastlower,2].mean()) if len(lastlower) else None;drop=float(held[:,2].mean()-lowerz) if len(held) and lowerz is not None else None;departure=(root[-1,:2]-root[np.flatnonzero(exitmask)[0],:2]).tolist() if exitmask.any() else [0.,0.];command=r['scene']['reach_command_human_m'];task=r['scene'].get('exit_task','none');exitdistance=float(np.linalg.norm(departure));success=bool(r['physical_complete'] and holdlongest*.02>=.5 and drop is not None and drop>.10 and (task=='none' or exitdistance>.25))
measured=float(measure[hold].mean()) if hold.any() else None;command_error=abs(measured-command) if measured is not None else None;hold_root_error=float(np.linalg.norm(root[hold,:2]-r['scene']['goal_xy'],axis=-1).mean()) if hold.any() else None;right=np.array([forward[1],-forward[0]]);signed_exit=float(-np.dot(departure,forward[:2]) if task=='back_walk' else np.dot(departure,right) if task=='sidestep' else 0.);command_pass=command_error is not None and command_error<=.08;position_pass=hold_root_error is not None and hold_root_error<.15;exit_pass=task=='none' or signed_exit>.25;interaction_success=success;success=bool(success and command_pass and position_pass and exit_pass)
exitids=np.flatnonzero(exitmask);exitsegment=(root[exitids[-1],:2]-root[exitids[0],:2]) if len(exitids)>1 else np.zeros(2);exitspan=(len(exitids)-1)*.02;exitquantity=(float(-np.dot(exitsegment,forward[:2]))/max(exitspan,.02) if task=='back_walk' else float(np.dot(exitsegment,right)) if task=='sidestep' else 0.)*1.2701193988323212/1.0486437524221748
report=dict(exit_command=r['scene'].get('exit_command',0.),actual_exit_quantity_human_equiv=exitquantity,exit_observed_duration_s=exitspan,success=success,interaction_success=interaction_success,command_error_m=command_error,command_pass=command_pass,position_pass=position_pass,exit_pass=exit_pass,signed_exit_distance_m=signed_exit,physical_complete=r['physical_complete'],command_human_equiv_m=command,actual_hold_wrist_forward_human_equiv_m=float(measure[hold].mean()) if hold.any() else None,actual_reach_wrist_forward_p95_human_equiv_m=float(np.quantile(measure[reach],.95)) if reach.any() else None,hold_palm_mean=held.mean(0).tolist() if len(held) else None,hold_palm_std=held.std(0).tolist() if len(held) else None,longest_table_contact_s=longest*.02,longest_hold_contact_s=holdlongest*.02,contact_during_hold_s=float((flags&hold).sum()*.02),hand_lowering_m=drop,exit_task=task,exit_displacement_xy=departure,exit_distance_m=exitdistance,mean_hold_root_error_m=float(np.linalg.norm(root[hold,:2]-r['scene']['goal_xy'],axis=-1).mean()) if hold.any() else None,scope='Command is mean forward wrist reach during generated hold in human-equivalent metres; success requires consecutive50Hz sampled top contact within the held phase. Completion allows hand release/departure; old terminal-hand-at-table success is not used.');(run/'command_metrics.json').write_text(json.dumps(report,indent=2));print(json.dumps(report,indent=2))
