import json,numpy as np
from scipy.spatial.transform import Rotation
from pathlib import Path
R=Path('/home/pku/frankenmotion');O=R/'outputs_amass/smpl_visual_audit_20261007';O.mkdir(exist_ok=True)
rows=json.loads((R/'outputs_amass/universal_tracker_20261006/general_evaluation/fresh_candidate/audited_results.json').read_text());records=[]
for row in rows:
 z=np.load(row['path']);p=z['joints_zup_m'];root=p[:,0];v=(p[:,16]+p[:,17])/2-root;v=v/np.maximum(np.linalg.norm(v,axis=-1,keepdims=True),1e-9);tilt=np.degrees(np.arccos(np.clip(v[:,2],-1,1)));step=np.degrees(np.arccos(np.clip((v[1:]*v[:-1]).sum(-1),-1,1)));side=p[:,1,:2]-p[:,2,:2];yaw=np.unwrap(np.arctan2(side[:,1],side[:,0]));dy=root[:,1]-root[0,1]
 hip=p[:,1]-p[:,2];yy=hip-(hip*v).sum(-1,keepdims=True)*v;yy/=np.maximum(np.linalg.norm(yy,axis=-1,keepdims=True),1e-9);xx=np.cross(yy,v);rot=Rotation.from_matrix(np.stack([xx,yy,v],axis=-1));fullstep=np.degrees((rot[1:]*rot[:-1].inv()).magnitude());rootrot=Rotation.from_rotvec(z['poses_axisangle'][:,:3]);rootstep=np.degrees((rootrot[1:]*rootrot[:-1].inv()).magnitude())
 records.append(dict(task=row['task'],source=row['source'],command=row['command'],path=row['path'],first_tilt_deg=float(tilt[0]),last_tilt_deg=float(tilt[-1]),maximum_tilt_deg=float(tilt.max()),max_adjacent_torso_change_deg=float(step.max()),max_adjacent_torso_orientation_change_deg=float(fullstep.max()),max_adjacent_root_rotation_change_deg=float(rootstep.max()),max_tilt_increase_from_start_deg=float(tilt.max()-tilt[0]),pelvis_drop_from_start_m=float(root[0,2]-root[:,2].min()),min_pelvis_z_m=float(root[:,2].min()),maximum_root_speed_m_s=float(np.linalg.norm(np.diff(root,axis=0),axis=-1).max()*20),net_unwrapped_yaw_deg=float(np.degrees(yaw[-1]-yaw[0])),yaw_range_deg=float(np.degrees(np.ptp(yaw))),leftward_peak_m=float(max(0,dy.max())),rightward_peak_m=float(max(0,-dy.min())),human_event_pass=bool(row['human']['event_pass']),human_quantity=row['human']['quantity'],g1_actual=row['actual']))
summary={}
for t in sorted(set(r['task'] for r in records)):
 a=[r for r in records if r['task']==t];summary[t]=dict(n=len(a),endpoint_tilt_gt45=sum(max(r['first_tilt_deg'],r['last_tilt_deg'])>45 for r in a),initial_tilt_gt90=sum(r['first_tilt_deg']>90 for r in a),drop_gt25cm=sum(r['pelvis_drop_from_start_m']>.25 for r in a),torso_step_gt30deg_50ms=sum(r['max_adjacent_torso_change_deg']>30 for r in a),torso_orientation_step_gt30deg_50ms=sum(r['max_adjacent_torso_orientation_change_deg']>30 for r in a),root_rotation_step_gt30deg_50ms=sum(r['max_adjacent_root_rotation_change_deg']>30 for r in a),max_torso_orientation_step_deg=max(r['max_adjacent_torso_orientation_change_deg'] for r in a),tilt_increase_gt30deg=sum(r['max_tilt_increase_from_start_deg']>30 for r in a),min_pelvis_z_m=min(r['min_pelvis_z_m'] for r in a),max_root_speed_m_s=max(r['maximum_root_speed_m_s'] for r in a),net_turn_over360=sum(abs(r['net_unwrapped_yaw_deg'])>360 for r in a),yaw_excursion_over360=sum(r['yaw_range_deg']>360 for r in a),left_peak_exceeds_right_5cm=sum(r['leftward_peak_m']>r['rightward_peak_m']+.05 for r in a),human_event_fail=sum(not r['human_event_pass'] for r in a))
(O/'human_audit.json').write_text(json.dumps(dict(scope='880 frozen main-test raw human motions,80 per task. Diagnostic thresholds explicitly defined here; not exact reproduction of collaborator 144-case protocol. No comparison to unedited source, so no claim about newly introduced changes. Absolute nominal Z not a physical ground-contact certificate. No squat in11-taskset. No self-intersection or full semantic sequence validation.',summary=summary,records=records),indent=2));print(json.dumps(summary,indent=2))
