"""Generated turn/away clips appended to generated reach; no turn pose correction."""
import sys,json,shutil,argparse,numpy as np
from pathlib import Path
from scipy.spatial.transform import Rotation,Slerp
R=Path('/home/pku/frankenmotion');D=R/'outputs_amass/turn_demo_20261005';sys.path.insert(0,str(R/'work'));import unified_retarget_20261004 as rt
p=argparse.ArgumentParser();p.add_argument('--name',default='development_v1');a=p.parse_args();out=D/a.name;out.mkdir(exist_ok=False);rt.init()
def blend(q0,q1,n):
 u=np.linspace(0,1,n+1)[1:];u=u*u*(3-2*u);q=q0[None]+u[:,None]*(q1-q0)[None];q[:,3:7]=Slerp([0,1],Rotation.from_quat(np.array([q0,q1])[:,[4,5,6,3]]))(u).as_quat()[:,[3,0,1,2]];return q
def place(q,anchor):
 q=q.copy();yaw=Rotation.from_quat(anchor[[4,5,6,3]]).as_euler('xyz')[2]-Rotation.from_quat(q[0,[4,5,6,3]]).as_euler('xyz')[2];r=Rotation.from_euler('z',yaw);offset=q[0,:3].copy();offset[2]=0;shift=anchor[:3].copy();shift[2]=0;q[:,:3]=r.apply(q[:,:3]-offset)+shift;q[:,3:7]=(r*Rotation.from_quat(q[:,[4,5,6,3]])).as_quat()[:,[3,0,1,2]];return q
def settle(q):
 st=q[-1].copy();st[7:]=rt.g.tr.rt.Q0;st[3:7]=Rotation.from_euler('z',Rotation.from_quat(st[[4,5,6,3]]).as_euler('xyz')[2]).as_quat()[[3,0,1,2]];d=rt.g.tr.mujoco.MjData(rt.g.M);d.qpos[:]=st;rt.g.tr.rt.floor_align(rt.g.M,d);st[2]=d.qpos[2];return np.r_[q,blend(q[-1],st,30),np.repeat(st[None],20,axis=0)]
def retime(q,n):
 at=np.linspace(0,len(q)-1,n);out=np.stack([np.interp(at,np.arange(len(q)),v) for v in q.T],1);out[:,3:7]=Slerp(np.arange(len(q)),Rotation.from_quat(q[:,[4,5,6,3]]))(at).as_quat()[:,[3,0,1,2]];return out
awaydir=D/'away_dev/scene_000';am=json.loads((awaydir/'reference_contact.json').read_text());away=np.load(awaydir/'reference_contact.npz')['reference_qpos'];lo,hi=am['segments']['walk'];away=retime(away[lo:hi],round((1.2/.45+.8)*20));turns={}
for deg in [90,135]:turns[deg]=rt.g.convert(np.load(D/f'turn_probe/turn_81005000_{deg}.npz'),'uniform')
source=R/'outputs_amass/reach_demo_20261005/development_v10';rows=[]
for i,row in enumerate(json.loads((source/'manifest.json').read_text())):
 old=Path(row['source']);dest=out/f'scene_{i:03d}';dest.mkdir();meta=json.loads((old/'reference_contact.json').read_text());seg=meta['segments'];q=np.load(old/'reference_contact.npz')['reference_qpos'][:seg['reach_hold'][1]].copy();seg={k:v for k,v in seg.items() if not k.startswith('exit')};deg=[90,135,90][i//2];begin=len(q);q=settle(q);seg['post_reach_settle']=[begin,len(q)];turn=place(turns[deg],q[-1]);start=len(q)+20;q=np.r_[q,blend(q[-1],turn[0],20),turn];seg['turn']=[start,len(q)];begin=len(q);q=settle(q);seg['post_turn_settle']=[begin,len(q)];depart=place(away,q[-1]);start=len(q)+20;q=np.r_[q,blend(q[-1],depart[0],20),depart];seg['away']=[start,len(q)];seg['exit']=seg['away'];stand=q[-1].copy();stand[7:]=rt.g.tr.rt.Q0;stand[3:7]=Rotation.from_euler('z',Rotation.from_quat(stand[[4,5,6,3]]).as_euler('xyz')[2]).as_quat()[[3,0,1,2]];dd=rt.g.tr.mujoco.MjData(rt.g.M);dd.qpos[:]=stand;rt.g.tr.rt.floor_align(rt.g.M,dd);stand[2]=dd.qpos[2];start=len(q);q=np.r_[q,blend(q[-1],stand,30),np.repeat(stand[None],30,axis=0)];seg['exit_settle']=[start,len(q)];row=dict(row,source=str(dest),source_reach=str(old),exit_task='none',turn_command_deg=deg,away_command_robot_m=1.2,turn_generator_source=str(D/f'turn_probe/turn_81005000_{deg}.npz'),away_generator_source=str(awaydir/'human_walk.npz'),departure_task='turn_then_walk');row['reference_final_xy']=q[-1,:2].tolist();shutil.copy2(old/'human_reach.npz',dest/'human_reach.npz');shutil.copy2(D/f'turn_probe/turn_81005000_{deg}.npz',dest/'human_turn.npz');shutil.copy2(awaydir/'human_walk.npz',dest/'human_away.npz');np.savez_compressed(dest/'reference_contact.npz',reference_qpos=q,fps=20.);(dest/'scene.json').write_text(json.dumps(row,indent=2));meta.update(segments=seg,reference_frames=len(q),scope='Existing generated reach unchanged; generated turn command and generated distance-controlled forward departure via uniform GMR. Rigid XY/yaw placement, inter-clip blends, walk-only retiming and nominal final stance; no post-generation turn-angle correction. Legacy exit_task none prevents old side/back scoring; turn_metrics supplies actual new task success.');(dest/'reference_contact.json').write_text(json.dumps(meta,indent=2));rows.append(row);print(i,deg,len(q),flush=True)
(out/'manifest.json').write_text(json.dumps(rows,indent=2))
